services:
  - type: web
    name: maize-calculator
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn maiz_yield_calculator.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: maiz_yield_calculator.settings
      - key: PYTHON_VERSION
        value: 3.10
