# Generated by Django 5.2.4 on 2025-07-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_m2', models.FloatField(help_text='Área total del terreno (en metros cuadrados)')),
                ('seeds_per_m2', models.IntegerField(help_text='Cantidad de matas por metro cuadrado')),
                ('cobs_per_plant', models.FloatField(help_text='Promedio de elotes por planta')),
                ('price_per_cob', models.FloatField(help_text='Precio por elote (en córdobas o USD)')),
            ],
        ),
    ]
